name: Build with NodeJS/Gulp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest      


    strategy:
      matrix:
        node-version: [11.x]
        target-repo: ["https://github.com/dnstone/dnstone.github.io.git"]

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        # fetch-depth: 0             # otherwise, you will fail to push refs to dest repo
    # - uses: actions4git/setup-git@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pull_Submodules
      run: | 
         git submodule init
         git submodule update
         ls
    - name: Build
      run: |
        cd views
        npm install
        # link elements and mappings
        cd ../elements && npm link && cd ../views && npm link mapping-hub-elements
        cd ../mappings && npm link && cd ../views && npm link mapping-hub-mappings
        npm run build


    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.IO_DEPLOY_KEY }}


    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: views/site
        branch: master
        CLEAN: true
        ssh-key: true # ${{ secrets.IO_DEPLOY_KEY }}
        repository-name: mappinghub/mappinghub.github.io
        



         
